// Write a C program (we'll refer to it as A) that creates a child process B. Process B generates one random number N between 100 and 1000. Process A keeps generating and sending random numbers between 50 and 1050 to B until the absolute difference between the number generated by A and the number generated by B is less than 50. B prints the generated numbers and all the received numbers. A will print at the end the number of numbers generated until the stop condition was met.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <math.h>

int main(int argc, char *argv[])
{
  int p2c[2], c2p[2], n;
  if (pipe(p2c) < 0 || pipe(c2p) < 0)
  {
    perror("pipe");
    exit(1);
  }
  int f = fork();
  if (f < 0)
  {
    perror("fork");
    close(p2c[0]);
    close(p2c[1]);
    close(c2p[0]);
    close(c2p[1]);
    exit(1);
  }
  else if (f == 0)
  {
    close(p2c[1]);
    close(c2p[0]);
    srand(time(NULL));
    n = rand() % 901 + 100;
    int guess;
    printf("B generated %d\n", n);
    while (1)
    {
      if (read(p2c[0], &guess, sizeof(int)) < 0)
      {
        perror("B read");
        close(p2c[0]);
        exit(1);
      }
      int diff = abs(guess - n);
      printf("B received %d; difference is: %d\n", guess, diff);
      if (write(c2p[1], &diff, sizeof(int)) < 0)
      {
        perror("B write");
        close(c2p[1]);
        exit(1);
      }
      if (diff < 50)
        break;
      sleep(1);
    }
    close(p2c[0]);
    close(c2p[1]);
    exit(0);
    // Process B
  }
  else
  {
    int cnt = 0;
    close(p2c[0]);
    close(c2p[1]);
    int diff = 100;
    srand(time(NULL));
    while (1)
    {
      cnt++;
      int guess = rand() % 1001 + 50;
      if (write(p2c[1], &guess, sizeof(int)) < 0)
      {
        perror("A write");
        close(p2c[1]);
        close(c2p[0]);
        exit(1);
      }
      if (read(c2p[0], &diff, sizeof(int)) < 0)
      {
        perror("A read");
        close(p2c[1]);
        close(c2p[0]);
        exit(1);
      }
      if (diff < 50)
      {
        printf("A generated %d numbers\n", cnt);
        break;
      }
    }
    close(p2c[1]);
    close(c2p[0]);
    wait(NULL);
  }
  return 0;
}