// Write a C program named A that creates 3 child processes named B, C and D. A generates a random number between 10 and 20 and sends it to process D. Processes B and C keep generating numbers between 1 and 200 and send them to process D which calculates their difference. The processes stop when the absolute difference between the numbers generated by B and C is less or equal to the number generated by process A.
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/types.h>
#include <sys/time.h>
#include <math.h>

int main(int argc, char *argv[])
{
  int a2d[2], b2d[2], c2d[2], d2b[2], d2c[2], n;
  if (pipe(a2d) < 0 || pipe(b2d) < 0 || pipe(c2d) < 0 || pipe(d2b) < 0 || pipe(d2c) < 0)
  {
    perror("pipe");
    exit(1);
  }
  srand(getpid());
  n = rand() % 11 + 10;
  int f1 = fork();
  if (f1 < 0)
  {
    perror("fork");
    exit(1);
  }
  else if (f1 == 0)
  {
    close(a2d[0]);
    close(a2d[1]);
    close(b2d[0]);
    close(c2d[1]);
    close(c2d[0]);
    close(d2b[1]);
    close(d2c[1]);
    close(d2c[0]);
    srand(getpid());
    int b_guess;
    while (1)
    {
      b_guess = rand() % 201 + 1;
      if (write(b2d[1], &b_guess, sizeof(int)) < 0)
      {
        perror("B write");
        close(b2d[1]);
        close(d2b[0]);
        exit(1);
      }
      int stop = 0;
      if (read(d2b[0], &stop, sizeof(int)) < 0)
      {
        perror("B read");
        close(b2d[1]);
        close(d2b[0]);
        exit(1);
      }
      if (stop)
        break;
    }
    close(b2d[1]);
    close(d2b[0]);
    exit(0);
  }
  else
  {
    int f2 = fork();
    if (f2 < 0)
    {
      perror("fork");
      exit(1);
    }
    else if (f2 == 0)
    {
      close(a2d[0]);
      close(a2d[1]);
      close(b2d[0]);
      close(b2d[1]);
      close(c2d[0]);
      close(d2b[0]);
      close(d2b[1]);
      close(d2c[1]);
      srand(getpid());
      int c_guess;
      while (1)
      {
        c_guess = rand() % 201 + 1;
        if (write(c2d[1], &c_guess, sizeof(int)) < 0)
        {
          perror("C write");
          close(c2d[1]);
          close(d2c[0]);
          exit(1);
        }
        int stop = 0;
        if (read(d2c[0], &stop, sizeof(int)) < 0)
        {
          perror("C read");
          close(c2d[1]);
          close(d2c[0]);
          exit(1);
        }
        if (stop)
          break;
      }
      close(b2d[1]);
      close(d2b[0]);
      exit(0);
    }
    else
    {
      int f3 = fork();
      if (f3 < 0)
      {
        perror("fork");
        exit(1);
      }
      else if (f3 == 0)
      {
        // Process D
        close(a2d[1]);
        close(b2d[1]);
        close(c2d[1]);
        close(d2b[0]);
        close(d2c[0]);
        int b_guess = 50, c_guess = 0, diff;
        if (read(a2d[0], &diff, sizeof(int)) < 0)
        {
          perror("D read");
          close(a2d[0]);
          close(b2d[0]);
          close(c2d[0]);
          close(d2b[1]);
          close(d2c[1]);
          exit(1);
        }
        printf("Received %d from A\n", diff);
        while (abs(b_guess - c_guess) >= diff)
        {
          if (read(b2d[0], &b_guess, sizeof(int)) < 0)
          {
            perror("D read from B");
            close(a2d[0]);
            close(b2d[0]);
            close(c2d[0]);
            close(d2b[1]);
            close(d2c[1]);
            exit(1);
          }
          if (read(c2d[0], &c_guess, sizeof(int)) < 0)
          {
            perror("D read from C");
            close(a2d[0]);
            close(b2d[0]);
            close(c2d[0]);
            close(d2b[1]);
            close(d2c[1]);
            exit(1);
          }
          printf("B sent %d, C sent %d\n", b_guess, c_guess);
          int stop_sgn = 0;
          if (abs(b_guess - c_guess) < diff)
            stop_sgn = 1;
          if (write(d2b[1], &stop_sgn, sizeof(int)) < 0)
          {
            perror("D write to B");
            close(a2d[0]);
            close(b2d[0]);
            close(c2d[0]);
            close(d2b[1]);
            close(d2c[1]);
            exit(1);
          }
          if (write(d2c[1], &stop_sgn, sizeof(int)) < 0)
          {
            perror("D write to C");
            close(a2d[0]);
            close(b2d[0]);
            close(c2d[0]);
            close(d2b[1]);
            close(d2c[1]);
            exit(1);
          }
        }
        printf("B and C are close enough, D is done\n");
        close(a2d[0]);
        close(b2d[0]);
        close(c2d[0]);
        close(d2b[1]);
        close(d2c[1]);
        exit(0);
      }
      else
      {
        close(a2d[0]);
        close(b2d[1]);
        close(b2d[0]);
        close(c2d[1]);
        close(c2d[0]);
        close(d2b[1]);
        close(d2b[0]);
        close(d2c[1]);
        close(d2c[0]);
        if (write(a2d[1], &n, sizeof(int)) < 0)
        {
          perror("A write");
          close(a2d[1]);
          exit(1);
        }
        printf("Sent %d to D\n", n);
        close(a2d[1]);
        wait(NULL);
        wait(NULL);
        wait(NULL);
      }
    }
  }
  return 0;
}