-- Dirty Reads Part 1
BEGIN TRANSACTION
UPDATE Courses SET CourseName='Mathematics 101 tran 1' WHERE CourseID=11
WAITFOR DELAY '00:00:10' 
ROLLBACK TRANSACTION

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
SELECT * FROM Courses
WAITFOR DELAY '00:00:15' SELECT * FROM Courses COMMIT TRAN

SET TRANSACTION ISOLATION LEVEL READ COMMITTED 
BEGIN TRAN
SELECT * FROM Courses
WAITFOR DELAY '00:00:15' 
SELECT * FROM Courses
COMMIT TRAN