BEGIN TRAN
WAITFOR DELAY '00:00:10'
INSERT INTO Students (StudentName) VALUES ('tu')
COMMIT TRAN

-- Phantom Reads 
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Students
WAITFOR DELAY '00:00:10' 
SELECT * FROM Students COMMIT TRAN

-- Solution
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM Students
WAITFOR DELAY '00:00:10' 
SELECT * FROM Students COMMIT TRAN