-- Console 1
select * from Medication

insert into Medication values (4, 'A', 'With care')

BEGIN TRANSACTION
WAITFOR DELAY '00:00:10'
UPDATE Medication SET Name='A' WHERE Name = 'B'
COMMIT TRANSACTION

-- Console 2
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
SELECT * FROM Medication
WAITFOR DELAY '00:00:15'
SELECT * FROM Medication
COMMIT TRANSACTION

-- Console 2
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT * FROM Medication
WAITFOR DELAY '00:00:10'
SELECT * FROM Medication
COMMIT TRANSACTION
